version: '3'

services:
  jekyll:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - gem_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --force_polling --livereload --host 0.0.0.0

volumes:
  gem_cache: