version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: academicpages
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --watch --force_polling --verbose --livereload --trace --incremental

volumes:
  gem_cache: